package com.unittest.unittest.model;

import java.util.Date;

/**
 * 后台管理员
 * generated by https://www.ixushu.com
 *
 */
public class Admin implements java.io.Serializable{


	private static final long serialVersionUID = 1L;

	private String id;
	/**
	 * 用户名
	 */
	private String userName;
	/**
	 * 密码
	 */
	private String passWd;
	/**
	 * 1超级管理员 2普通管理员 3普通操作员
	 */
	private Integer adminType;
	/**
	 * 真实姓名
	 */
	private String realName;
	/**
	 * 创建时间
	 */
	private Date createTime;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassWd() {
		return passWd;
	}
	public void setPassWd(String passWd) {
		this.passWd = passWd;
	}
	public Integer getAdminType() {
		return adminType;
	}
	public void setAdminType(Integer adminType) {
		this.adminType = adminType;
	}
	public String getRealName() {
		return realName;
	}
	public void setRealName(String realName) {
		this.realName = realName;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
}
