package com.unittest.unittest.model;

import com.xushuzn.common.dao.AbstractPO;
/**
 * ExpectResult实体类
 * Generated by https://www.ixushu.com
 */
public class ExpectResult extends AbstractPO {
    private static final long serialVersionUID = 1L;

    
    /**
     * 
     */
    private java.lang.String id;
    
    /**
     * 测试用例名称
     */
    private java.lang.String name;
    
    /**
     * 期望值
     */
    private java.lang.String jsonresult;

    public java.lang.String getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public void setId(java.lang.String id, boolean forceUpdate) {
        setId(id);

        if (forceUpdate) {
          addForceUpdateProperty("id");
        }
    }

    public java.lang.String getName() {
        return name;
    }

    /**
     * 测试用例名称
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    public void setName(java.lang.String name, boolean forceUpdate) {
        setName(name);

        if (forceUpdate) {
          addForceUpdateProperty("name");
        }
    }

    public java.lang.String getJsonresult() {
        return jsonresult;
    }

    /**
     * 期望值
     */
    public void setJsonresult(java.lang.String jsonresult) {
        this.jsonresult = jsonresult;
    }

    public void setJsonresult(java.lang.String jsonresult, boolean forceUpdate) {
        setJsonresult(jsonresult);

        if (forceUpdate) {
          addForceUpdateProperty("jsonresult");
        }
    }
}
