package com.unittest.unittest.model;

import com.xushuzn.common.dao.AbstractPO;
/**
 * TestCase实体类
 * Generated by https://www.ixushu.com
 */
public class TestCase extends AbstractPO {
    private static final long serialVersionUID = 1L;

    
    /**
     * 
     */
    private java.lang.String id;
    
    /**
     * 用例名称
     */
    private java.lang.String name;
    
    /**
     * 描述
     */
    private java.lang.String desc;

    public java.lang.String getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public void setId(java.lang.String id, boolean forceUpdate) {
        setId(id);

        if (forceUpdate) {
          addForceUpdateProperty("id");
        }
    }

    public java.lang.String getName() {
        return name;
    }

    /**
     * 用例名称
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    public void setName(java.lang.String name, boolean forceUpdate) {
        setName(name);

        if (forceUpdate) {
          addForceUpdateProperty("name");
        }
    }

    public java.lang.String getDesc() {
        return desc;
    }

    /**
     * 描述
     */
    public void setDesc(java.lang.String desc) {
        this.desc = desc;
    }

    public void setDesc(java.lang.String desc, boolean forceUpdate) {
        setDesc(desc);

        if (forceUpdate) {
          addForceUpdateProperty("desc");
        }
    }
}
